<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYhhxREK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYhhxREK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYhhxREK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYhhxREK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYhhxREK\App_KernelDevDebugContainer([
    'container.build_hash' => 'YhhxREK',
    'container.build_id' => 'd3ed0e6f',
    'container.build_time' => 1713705803,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYhhxREK');
